Player.create(name: "Tim Howard", position: "GK")
Player.create(name: "Mohammed Salah", position: "Mid")
Player.create(name: "Ronaldo", position: "Forward")
Player.create(name: "Lionel Messi", position: "Forward")
Player.create(name: "Romelu Lukaku", position: "Forward")
Player.create(name: "Sergio Ramos", position: "Defender")
Player.create(name: "Luis Suarez", position: "Forward")
Player.create(name: "Neymar, Jr.", position: "Mid")
Player.create(name: "Carlos Vela", position: "Forward")
Player.create(name: "Gerard Pique", position: "Defender")
Player.create(name: "Gianluigi Buffon", position: "GK")

Team.create(name: "Everton", city: "Liverpool")
Team.create(name: "Liverpool", city: "Liverpool")
Team.create(name: "Juventus", city: "Turin")
Team.create(name: "FC Barcelona", city: "Barcelona")
Team.create(name: "Manchester United", city: "Manchester")
Team.create(name: "Real Madrid", city: "Madrid")
Team.create(name: "FC Barcelona", city: "Barcelona")
Team.create(name: "PSG", city: "Paris")
Team.create(name: "LA Galaxy", city: "Los Angeles")
Team.create(name: "FC Barcelona", city: "Barcelona")
Team.create(name: "PSG", city: "Paris")

League.create(name: "English Primier League" nation: "England")
League.create(name: "La Liga" nation: "Spain")
League.create(name: "Lige 1" nation: "France")
League.create(name: "US Major League Soccer" nation: "USA")
League.create(name: "Serie a" nation: "Italy")
